sudo: false
language: minimal
 
addons:
  apt:
    packages:
      - luarocks

install: luarocks install --local luacheck

before_script:
  - /home/travis/.luarocks/bin/luacheck . --no-color -q
  - curl -sO https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh

script:
  - bash release.sh -w 23631
  - bash release.sh -g 1.13.2

branches:
  only:
    - /^[vV]?\d+\.\d+(\.\d+)?(-\S*)?$/
