sudo: false
language: minimal
 
before_script:
  - curl -sO https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh

script:
  - bash release.sh -w 23631
  - bash release.sh -g 1.13.4

branches:
  only:
    - /^[vV]?\d+\.\d+(\.\d+)?(-\S*)?$/
